### ISSUE TITLE
Config not saving LegitScaffold Settings

### ISSUE THREAD

**Issue by Faabyy** [Cvrws/Haru#83]
### Haru Build/Version

2.38

### Operating System

Windows 10

### Describe the bug

When I save a config with certain LegitScaffold settings, it works. When I load the conifg, the setting Shift Time is being reset to default settings. 

### Steps to reproduce

Create Config
Change LegitScaffold Shift Time setting
Save config
Load config

### Client Log

```shell
None
```

**Comment by Cvrws** [comment]
Use sakura instead in my readme is the server invitation, it will be free and all but it will not be open src anymore.
